[project]
name = "transit-cam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pygame>=2.6.1",
    "pyyaml>=6.0.2",
]

[project.scripts]
star-generator = "transit_cam.executables.star_generator:main"
transit-cam = "transit_cam.executables.transit_cam:main"
analyze-transit = "transit_cam.executables.analyze_transit:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
